apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations: 
    run.googleapis.com/launch-stage: ALPHA
    run.googleapis.com/ingress: internal-and-cloud-load-balancing 
  name: ${CONTAINER_SERVICE}
spec:
  template:
    metadata:      
      name: ${CONTAINER_SERVICE}-${REVISION_TAG} 
      annotations:
        run.googleapis.com/execution-environment: gen1
        autoscaling.knative.dev/minScale: '3'
        autoscaling.knative.dev/maxScale: '100'
      labels: 
        region:us-east4
        app_code:test
        classification:test
        cost_id:test
        department_id:test
        hca_project_id:test
        tco_id:test
        app_environment:dev
    spec:
      containerConcurrency: 80
      serviceAccountName: ${CLOUD_RUN_SA}
      containers:
      - image: ${CONTAINER_IMAGE}
        name: ${CONTAINER_SERVICE}
        ports: 
        - name: http1
          containerPort: 8080
        env:
        - name: PROJECT_ID
          value: ${PROJECT_ID}
        - name: DB_USER
          value: test
        - name: DB_NAME
          value: default
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: TEST
              key: "3"

      # It is recommended to use the latest version of the Cloud SQL Auth Proxy
      # Make sure to update on a regular schedule!
      - image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.1.0
        name: cloud-sql-proxy
        args:
        # Enable structured logging with LogEntry format:
        - "--structured-logs"

        # Replace DB_PORT with the port the proxy should listen on
        - "--port=1433"
        - "arched-inkwell-368821:us-east4:mssql"
        resources:
          limits:
            memory: "2Gi"
            cpu:    "1"
  traffic:
  - percent: 100
    latestRevision: true
