apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${FRONTEND_SERVICE}
spec: #TODO: labels
  template:
    metadata:
      name: ${FRONTEND_SERVICE}-yellow #TODO: change naming 
      annotations:
        autoscaling.knative.dev/minScale: '3'
        autoscaling.knative.dev/maxScale: '100'
    spec:
      containerConcurrency: 80
      # serviceAccountName: test #TODO insert sa name 
      containers:
      - image: ${FRONTEND_IMAGE}
        ports: 
        - name: http1
          containerPort: 8080
      - image: "gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.2.0" 
        env:
        - name: PROJECT_ID
          value: ${PROJECT_ID}
        - name: "EDITOR_UPSTREAM_RENDERER_URL"
          value: "todo output" #TODO secrets 

  traffic:
  - percent: 100
    latestRevision: true
