apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations: 
    run.googleapis.com/launch-stage: ALPHA 
  name: ${FRONTEND_SERVICE}
spec: #TODO: labels
  template:
    metadata:
      name: ${FRONTEND_SERVICE}-yellow #TODO: change naming 
      annotations:
        run.googleapis.com/execution-environment: gen1
        autoscaling.knative.dev/minScale: '3'
        autoscaling.knative.dev/maxScale: '100'
    spec:
      containerConcurrency: 80
      # serviceAccountName: test #TODO insert sa name 
      containers:
      - image: ${FRONTEND_IMAGE}
        name: frontend
        ports: 
        - name: http1
          containerPort: 8080
        env:
        - name: PROJECT_ID
          value: ${PROJECT_ID}
        - name: "EDITOR_UPSTREAM_RENDERER_URL"
          value: "todo output" #TODO secrets 

  traffic:
  - percent: 100
    latestRevision: true
