apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations: 
    run.googleapis.com/launch-stage: ALPHA
    run.googleapis.com/ingress: internal-and-cloud-load-balancing 
  name: ${CONTAINER_SERVICE}
spec: #TODO: labels
  template:
    metadata:
      name: ${CONTAINER_SERVICE}-${REVISION_TAG} 
      annotations:
        run.googleapis.com/execution-environment: gen1
        autoscaling.knative.dev/minScale: '3'
        autoscaling.knative.dev/maxScale: '100'
    spec:
      containerConcurrency: 80
      serviceAccountName: ${CLOUD_RUN_SA}
      containers:
      - image: ${CONTAINER_IMAGE}
        name: CONTAINER
        ports: 
        - name: http1
          containerPort: 8080
        env:
        - name: PROJECT_ID
          value: ${PROJECT_ID}
        - name: INSTANCE_CONNECTION_NAME
          value: "todo"
        - name: DB_NAME
          value: "todo"
        - name: DB_PORT
          value: "1433"
        - name: DB_USER
          value: "todo"
  traffic:
  - percent: 100
    latestRevision: true
