project_id="arched-inkwell-368821"
region="us-east4"
frontend_container_image = "us-east4-docker.pkg.dev/arched-inkwell-368821/reference-architectures/backend:latest"
frontend_service_name = "frontend"
backend_container_image = "us-east4-docker.pkg.dev/arched-inkwell-368821/reference-architectures/backend:latest"
backend_service_name = "backend"
