project_id            = "arched-inkwell-368821"
region                = "us-east4"
frontend_service_name = "new-new"
database_name         = "yktv"
domain_restricted_sharing_tag = "1067211650924"
partially_qualified_domain_name = "mytestapp.com"
repository_name = "chasinandrew/sample-code"