apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations: 
    run.googleapis.com/launch-stage: ALPHA
    run.googleapis.com/ingress: internal-and-cloud-load-balancing 
  name: ${SERVICE_NAME}
spec:
  template:
    metadata:      
      name: ${SERVICE_NAME}-${REVISION_TAG} 
      annotations:
        run.googleapis.com/execution-environment: gen1
        run.googleapis.com/vpc-access-egress: all-traffic
        run.googleapis.com/vpc-access-connector: projects/arched-inkwell-368821/locations/us-east4/connectors/pods-2
        autoscaling.knative.dev/minScale: '3'
        autoscaling.knative.dev/maxScale: '100'
      labels: 
        region: us-east4
        app_code: placeholder
        classification: placeholder
        cost_id: placeholder
        department_id: placeholder
        hca_project_id: placeholder
        tco_id: placeholder
        app_environment: dev 
    spec:
      containerConcurrency: 80
      serviceAccountName: ${CLOUD_RUN_SA}
      containers:
      - image: ${CONTAINER_IMAGE}
        name: ${SERVICE_NAME}
        ports: 
        - name: http1
          containerPort: 80
        env:
        - name: PROJECT_ID
          value: ${PROJECT_ID}
        - name: DB_USER 
          valueFrom:
            secretKeyRef:
              name: DB_USER 
              key: "1" 
        - name: DB_NAME 
          valueFrom:
            secretKeyRef:
              name: DB_NAME 
              key: "1"
        - name: DB_CONNECTION
          valueFrom:
            secretKeyRef:
              name: DB_NAME 
              key: "1"
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: DB_PASS  
              key: "1" 
     
  traffic: 
  - latestRevision: true
    percent: 100 