project_id                              = "hca-demo-qa"
region                                  = "us-east4"
frontend_service_name                   = "new-new"
database_name                           = "yktv"
domain_restricted_sharing_exclusion_tag = "1067211650924"
partially_qualified_domain_name         = "mytestapp.com"
repository_name                         = "chasinandrew/sample-code"