name: PLAN AND APPLY TERRAFORM
on:
  push:
    paths: 
    - 'terraform/**'
    branches:
    - 'feature/**'
    - 'develop-iac'
    - 'qa-iac'
    - 'main-iac'
  pull_request:
    paths: 
    - 'terraform/**'
    branches:
    - 'feature/**'
    - 'develop-iac'
    - 'qa-iac'
    - 'main-iac'

jobs:
  dev:
    uses: ./.github/workflows/_tf_infrastructure.yaml
    permissions: 
      id-token: write
      contents: read
    with: 
      environment: dev
      working_directory: ./terraform
      service_name: hello
      first_run: false
      workspace_name: cloud-run-reference-architecture
    secrets: inherit
  