name: PLAN AND APPLY TERRAFORM
on:
  push:
    paths: 
    - 'terraform/**'
    branches:
    - 'feature/**'
    - 'develop'
    - 'qa'
    - 'main'
  pull_request:
    paths: 
    - 'terraform/**'
    branches:
    - 'feature/**'
    - 'develop'
    - 'qa'
    - 'main'

jobs:
  dev:
    uses: ./.github/workflows/_tf_infrastructure.yaml
    permissions: 
      actions: read
      id-token: write
      contents: read
    with: 
      environment: dev-iac
      working_directory: ./terraform
      first_run: false
      workspace_name: cloud-run-reference-architecture
      terraform_org: google-testing-org
      project_id: arched-inkwell-368821
      region: us-east4
    secrets: inherit
  # qa:
  #   if: github.head_ref == 'develop' 
  #   uses: ./.github/workflows/_tf_infrastructure.yaml
  #   permissions: 
  #     actions: read
  #     id-token: write
  #     contents: read
  #   with: 
  #     environment: qa-iac
  #     working_directory: ./terraform
  #     service_name: hello
  #     first_run: false
  #     workspace_name: cloud-run-reference-architecture
  #     terraform_org: google-testing-org
  #     project_id: arched-inkwell-368821
  #     region: us-east4
  #   secrets: inherit
  